/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Appliances_Info;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        setLocation(400,200);
        setSize(970, 640);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcome1 = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        cms = new javax.swing.JLabel();
        main = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JCheckBox();
        note = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(940, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome1.setBackground(new java.awt.Color(0, 0, 0));
        welcome1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        welcome1.setForeground(new java.awt.Color(255, 255, 255));
        welcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome1.setText("Welcome");
        welcome1.setOpaque(true);
        jPanel1.add(welcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 200, -1));

        to.setBackground(new java.awt.Color(0, 0, 0));
        to.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        to.setForeground(new java.awt.Color(255, 255, 255));
        to.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        to.setText("To");
        to.setOpaque(true);
        jPanel1.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 80, -1));

        cms.setBackground(new java.awt.Color(0, 0, 0));
        cms.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        cms.setForeground(new java.awt.Color(255, 255, 255));
        cms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cms.setText("Car Management System");
        cms.setOpaque(true);
        jPanel1.add(cms, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 450, -1));

        main.setForeground(new java.awt.Color(255, 255, 51));
        main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Appliances_Info/login.png"))); // NOI18N
        jPanel1.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        login.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 90, 30));

        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Username :");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 80, 30));

        password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        password.setText("Password :");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 80, 30));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 260, 30));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 260, 30));

        showPassword.setForeground(new java.awt.Color(255, 255, 255));
        showPassword.setText("show password");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 130, -1));

        note.setForeground(new java.awt.Color(255, 255, 255));
        note.setText("Note: Username=admin, password= admin");
        jPanel1.add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, -1, -1));

        btnLogin.setBackground(new java.awt.Color(255, 0, 51));
        btnLogin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // To show password in password TextField.
        if(showPassword.isSelected())
        {
            txtPassword.setEchoChar((char)0);
        }
        else
        {
            txtPassword.setEchoChar('*');
        }
        
    }//GEN-LAST:event_showPasswordActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // To login into the main page.
        String username= txtUsername.getText();
        String password= txtPassword.getText();
        if(username.equals("admin") && password.equals("admin"))
        {
            new Appliances_Info().setVisible(true);
            this.setVisible(false);
        }
        else
        {
            if(txtUsername.getText().equals("") || txtPassword.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this,"Please Enter username and password");
            }
            else
            {
            txtUsername.setText("");
            txtPassword.setText("");
            JOptionPane.showMessageDialog(this,"Wrong username or password");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel cms;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel main;
    private javax.swing.JLabel note;
    private javax.swing.JLabel password;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JLabel to;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel username;
    private javax.swing.JLabel welcome1;
    // End of variables declaration//GEN-END:variables
}
